#!/usr/bin/env bash
# Idempotent Cloud Agent install for CE VAULT.
# Installs JS deps (root + bot dev-bridge), pre-warms the Firebase emulator JARs,
# and creates a local .env.local wired to the Firebase Emulator Suite if missing.
set -euo pipefail

cd "$(dirname "$0")/.."

echo "==> Installing root dependencies (npm ci)"
npm ci

echo "==> Installing bot dev-bridge dependencies (npm ci)"
npm --prefix bot ci

echo "==> Pre-warming Firebase emulator JARs"
# Downloads the Firestore/Storage emulator jars into the firebase-tools cache so the
# first `npm run emulators` on a fresh boot does not have to fetch them.
npx -y firebase-tools@latest setup:emulators:firestore || true
npx -y firebase-tools@latest setup:emulators:storage || true

if [ ! -f .env.local ]; then
  echo "==> Creating .env.local for the Firebase Emulator Suite (demo-ce-vault)"
  cat > .env.local <<'ENV'
# Local Firebase Emulator dev (project demo-ce-vault) — generated by .cursor/install.sh
NEXT_PUBLIC_FIREBASE_PROJECT_ID=demo-ce-vault
NEXT_PUBLIC_FIREBASE_API_KEY=demo-api-key
NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=demo-ce-vault.firebaseapp.com
NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=demo-ce-vault.appspot.com
NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=000000000000
NEXT_PUBLIC_FIREBASE_APP_ID=1:000000000000:web:demolocal
NEXT_PUBLIC_USE_FIREBASE_EMULATOR=1

FIREBASE_PROJECT_ID=demo-ce-vault
FIREBASE_STORAGE_BUCKET=demo-ce-vault.appspot.com
FIRESTORE_EMULATOR_HOST=127.0.0.1:8080
FIREBASE_STORAGE_EMULATOR_HOST=127.0.0.1:9199

APP_URL=http://localhost:3000
API_SECRET=

FEE_WARNING_THRESHOLD=3
DEFAULT_THB=5000
DEFAULT_SELL_RATE=35.5
DEFAULT_MARKET_RATE=34.8
DEFAULT_BANK_ACCOUNT_ID=
ENV
else
  echo "==> .env.local already present — leaving as-is"
fi

echo "==> install.sh complete"
